FROM node:20-alpine


WORKDIR /app
COPY backend/package*.json ./
RUN npm install --production


COPY backend ./


ENV PORT=3000
EXPOSE 3000


# In production we run Node directly (not nodemon)
CMD ["node", "server.js"]