name: Deploy to EC2 (MERN)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e

          # Clone repo if not exists, else pull latest
          if [ ! -d "/opt/finsathi/.git" ]; then
            echo "Cloning repo..."
            git clone https://github.com/prajwal9773/FinSathi.git /opt/finsathi
          else
            echo "Repo exists, pulling latest changes..."
            cd /opt/finsathi
            git reset --hard
            git pull origin main
          fi

          cd /opt/finsathi

          # Use your existing backend/.env (don’t overwrite)

          # Build & restart containers
          docker compose down || true
          docker compose up -d --build
          docker system prune -f

          